[package]
name = "dry-run-runtime-upgrade-api"
version = "0.1.0"
authors = ["kianenigma <kian.peymani@gmail.com>"]
edition = "2018"

[dependencies]
sp-api = { git = "https://github.com/paritytech/substrate", tag = "v2.0.1" }

[features]
default = [ "std" ]
std = [
	"sp-api/std",
]
