[package]
name = "pallet-protocol-fee-rpc-runtime-api"
version = "0.1.0"
authors = ["Polymath"]
edition = "2018"

[dependencies]
polymesh-common-utilities = { path = "../../../common", default-features = false }

# General
serde = { version = "1.0.104", optional = true, features = ["derive"] }

# Substrate
codec = { package = "parity-scale-codec", version = "1.2.0", default-features = false, features = ["derive"] }
sp-api = { git = 'https://github.com/paritytech/substrate', default_features = false, rev = "3f1341a384559ec046710e2f46eb4a7d9fc52f50"}
sp-runtime = { git = 'https://github.com/paritytech/substrate', default_features = false,  rev = "3f1341a384559ec046710e2f46eb4a7d9fc52f50"}
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "3f1341a384559ec046710e2f46eb4a7d9fc52f50" }

[dev-dependencies]
serde_json = "1.0.48"

[features]
default = ["std"]
std = [
    "serde",
    "sp-api/std",
    "codec/std",
    "sp-runtime/std",
    "frame-support/std",
    "polymesh-common-utilities/std"
]
