[package]
name = "pallet-staking-rpc-runtime-api"
version = "2.0.0"
authors = ["Anonymous"]
edition = "2018"

[dependencies]
sp-api = { git = 'https://github.com/paritytech/substrate', default_features = false, rev = "3f1341a384559ec046710e2f46eb4a7d9fc52f50"}
sp-runtime = { git = 'https://github.com/paritytech/substrate', default_features = false,  rev = "3f1341a384559ec046710e2f46eb4a7d9fc52f50"}
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, rev = "3f1341a384559ec046710e2f46eb4a7d9fc52f50" }

[dev-dependencies]
serde_json = "1.0.48"

[features]
default = ["std"]
std = [
	"sp-api/std",
	"sp-runtime/std",
	"frame-support/std"
]
