[package]
name = "pallet-confidential-asset"
version = "0.1.0"
authors = ["Polymath"]
edition = "2018"

[dependencies]
# Common
polymesh-primitives = { path = "../../primitives", default-features = false }
polymesh-primitives-derive = { path = "../../primitives_derive", default-features = false }
polymesh-common-utilities = { path = "../common", default-features = false }

# Our Pallets
pallet-identity = { path = "../identity", default-features = false }
pallet-portfolio = { path = "../portfolio", default-features = false }
pallet-statistics = { path = "../statistics", default-features = false }
pallet-asset = { path = "../asset", default-features = false  }
pallet-asset-types = { path = "../asset/types", default-features = false  }

# Crypto
cryptography = { path = "../../external/cryptography", default-features = false }
curve25519-dalek = { version = "2", default-features = false, features = ["nightly"] }

# Substrate
codec = { package = "parity-scale-codec", version = "1.1.0", default-features = false, features = ["derive"] }
frame-system = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "at-add-dispatch-call" }
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "at-add-dispatch-call" }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "at-add-dispatch-call" }

[features]
equalize = []
default = ["std"]
no_std = []
only-staking = []
std = [
    "pallet-asset-types/std",
    "sp-std/std",
    "polymesh-primitives/std",
    "frame-system/std",
    "frame-support/std",
]
