[package]
name = "polymesh-contracts"
version = "0.1.0"
authors = ["Polymath Inc."]
edition = "2018"

[dependencies]

# Substrate specific
frame-system = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "at-add-dispatch-call" }
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "at-add-dispatch-call" }
pallet-contracts = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "at-add-dispatch-call" }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "at-add-dispatch-call" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "at-add-dispatch-call" }
codec = { package = "parity-scale-codec", version = "1.3.0", default-features = false, features = ["derive"] }

# Polymesh specific
pallet-identity = { path = "../identity", deafult-features = false }
polymesh-primitives = { path = "../../primitives", default-features = false }
polymesh-common-utilities = { path = "../common", default-features = false }
pallet-protocol-fee = { path = "../protocol-fee", deafult-features = false }

[features]
equalize = []
default = ["std"]
no_std = []
std = [
    "codec/std",
    "sp-std/std",
    "sp-runtime/std",
    "frame-system/std",
    "frame-support/std",
    "pallet-identity/std",
    "pallet-contracts/std",
    "polymesh-primitives/std",
    "pallet-protocol-fee/std",
    "polymesh-common-utilities/std",
]